baseURL: https://pauline-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Pauline Cohen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Pauline Cohen
  blog: {}
  contact:
    address:
      - city: Paris
        country: France
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pcohen.mfa2022@london.edu 
        title: Email
    enable: yes
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/paulinecohenmfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/pauline-cohen-82318a170
  image: astronomy.jpg
  name: Pauline Cohen
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Cohen_Pauline.jpg
        subtitle: Nice to meet you
        title: About me
        url: blogs/resume
      - image: lbs_class_1.jpg
        subtitle: London Business School
        title: What I do now
        url: blogs/lbs
      - image: Nice.jpg
        subtitle: EDHEC Business School, Nice, France
        title: MSc in Financial Markets
        url: https://master.edhec.edu/msc-financial-engineering
      - image: Sunset.jpg
        subtitle: Sunset in San Diego
        title: Exchange program, San Diego, United States
        url: https://www.sandiego.edu
      - image: astronomy.jpg
        subtitle: Shoot for the moon. Even if you miss, you'll land among the stars.
        title: A passion for astronomy
        url: blogs/astronomy
      - image: cinema.jpg
        subtitle: Be ready...
        title: My favorite movie and director
        url: https://www.youtube.com/watch?v=Z5jvQwwHQNY
      - image: financial_markets.jpg
        subtitle: Estimating the volatility of stock markets
        title: R Studio Project 
        url: blogs/edhec  
      - image: montecarlo.jpg
        subtitle: Monte Carlo simulations
        title: R Studio Project
        url: blogs/montecarlo
      - image: assets.jpg
        subtitle: Illiquidity of Assets
        title: End of study Thesis
        url: blogs/Master_Project.pdf
     
      
    
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hello, thank you so much for visiting my website. I am Pauline and I did a MSc in Financial Markets in the South of France. I am currently enrolled in the Master in Financial Analysis at the London Business School and I am happy to show you various works I did at LBS but also during my previous master in France. Feel free to reach out if you have any questions."
    title: About me
    url: https://pauline-portfolio.netlify.app/blogs/resume/
