baseURL: https://pauline-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Pauline Cohen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Discover me
    subtitle: |-
      Welcome to my blog, feel free to reach out if you have questions!
    title: Hi, my name is Pauline Cohen
  blog: {}
  contact:
    formEmail:pcohen.mfa2022@london.edu
    address:
      - city: Paris
        country: France
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pcohen.mfa2022@london.edu 
        title: Email
    phone:
    - phone : +33 6 19 48 60 78
      title: Phone
    enable: yes
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/paulinecohenmfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/pauline-cohen-82318a170
  image: cover.jpg
  name: Pauline Cohen
  navigation:
    button1:
      - name: My storyline
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Get to know me
        url: https://pauline-portfolio.netlify.app/blogs/resume/
      - name: Master Thesis 
        url: blogs/Master_Project.pdf
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Cohen_Pauline.jpg
        subtitle: Nice to meet you
        title: Resume
        url: blogs/PaulineCohen_resume_LBS.pdf
      - image: lbs_class_1.jpg
        subtitle: London Business School
        title: What I do now
        url: blogs/now
      - image: Nice.jpg
        subtitle: EDHEC Business School, Nice, France
        title: MSc in Financial Markets
        url: https://master.edhec.edu/msc-financial-engineering
      - image: Sunset.jpg
        subtitle: Sunset in San Diego
        title: Exchange program, San Diego, United States
        url: blogs/sandiego
      - image: astronomy.jpg
        subtitle: Shoot for the moon. Even if you miss, you'll land among the stars.
        title: A passion for astronomy
        url: blogs/astronomy
      - image: cinema.jpg
        subtitle: Be ready...
        title: My favorite movie and director
        url: https://www.youtube.com/watch?v=Z5jvQwwHQNY
      - image: Bangkok.jpg
        subtitle: R Studio Project, London Business School
        title: A model to forecast Airbnb prices in Bangkok
        url: blogs/lbs_3
      - image: corona.jpg
        subtitle: R Studio Project, London Business School
        title: Can we predict recessions?
        url: blogs/lbs_1 
      - image: environnement.jpg
        subtitle: R Studio Project, London Business School
        title: Are global temperatures increasing?
        url: blogs/lbs_2
      - image: financial_markets.jpg
        subtitle: R Studio Project, EDHEC Business School
        title: Estimating the volatility of stock markets 
        url: blogs/edhec  
      - image: montecarlo.jpg
        subtitle: R Studio Project, EDHEC Business School
        title: Monte Carlo simulations
        url: blogs/montecarlo
      - image: assets.jpg
        subtitle: End of study Thesis, EDHEC Business School
        title: Illiquidity of Assets and their prices
        url: blogs/Master_Project.pdf
     
      
    
  two:
    buttonText: To know more about me
    enable: yes
    subtitle: "Hello, thank you so much for visiting my website. I am Pauline and I did a MSc in Financial Markets in the South of France. I am currently enrolled in the Master in Financial Analysis at the London Business School and I am happy to show you various works I did at LBS but also during my previous master in France. Feel free to reach out if you have any questions."
    title: About me
    url: https://pauline-portfolio.netlify.app/blogs/resume
