baseURL: https://infallible-bose-108675.netlify.app
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Pauline Cohen
  blog: {}
  contact:
    address:
      - city: Paris
        country: France
        street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pcohen.mfa2022@london.edu 
        title: Email
    enable: yes
    phone:
      - phone: +33 6 19 48 60 78
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School 
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/paulinecohenmfa
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/pauline-cohen-82318a170
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Cohen_Pauline.jpg
        subtitle: Nice to meet you
        title: Me
        url: blogs/me
      - image: Paris.jpg
        subtitle: Paris, France
        title: Where I am from 
        url: blogs/Paris
      - image: Nice.jpg
        subtitle: Nice, France
        title: Where I studied Finance
        url: blogs/Nice
      - image: London.jpg
        subtitle: London, United Kingdom
        title: Where I am now
        url: blogs/London
      - image: Sunset.jpg
        subtitle: Exchange program, San Diego, United States
        title: Sunset in San Diego
        url: blogs/Sunset
      - image: GrandCanyon.jpg
        subtitle: Grand Canyon, United States
        title: Discovering the wonders of the United States
        url: blogs/GrandCanyon
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hello, thank you so much for visiting my website. I am Pauline and I did a MSc in Financial Markets in the South of France. I am currently enrolled in the Master in Financial Analysis at the London Business School and I am happy to show you various works I did at LBS but also during my previous master in France. Feel free to reach out if you have any questions."
    showcase:
      image: stocks_market.jpg
        subtitle: "Hello, thank you so much for visiting my website. I am Pauline and I did a MSc in Financial Markets in the South of France. I am currently enrolled in the Master in Financial Analysis at the London Business School and I am happy to show you various works I did at LBS but also during my previous master in France. Feel free to reach out if you have any questions."
        url: blogs/stocks_market
        title: About me
